accounts/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from .views import (CustomLogoutView,
                    CustomLoginView,
                    CustomSignUpView,
                    UserProfileView,
                    UserProfileUpdateView,
                    UserPasswordResetView,
                    UserPasswordResetDoneView,
                    UserPasswordResetConfirmView,
                    UserPasswordResetCompleteView
                    )


app_name = 'accounts'
urlpatterns = [
    path('signup/', CustomSignUpView.as_view(), name = 'signup' ),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='edit'),

    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:post_pk>/<slug:post_slug>/', PostDetailView.as_view(), name='post_detail'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'), name='blog'),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    objects = None
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    is_published = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    categories = models.ManyToManyField(Category, related_name='posts')
    tags = models.ManyToManyField(Tag, related_name='posts')
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['-created_at']

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'post_pk': self.pk, 'post_slug': self.slug})

    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments')
    content = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def approve(self):
        self.approved = True
        self.save()

    def get_absolute_url(self):
        return self.post.get_absolute_url()

    def __str__(self):
        return f'Comment by {self.author.username} on {self.post.title}'

blog/forms.py
from django import forms
from .models import Post, Comment


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'is_published', 'categories','tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'post title'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'post content'}),
            'is_published': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'categories': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'comment content', 'rows': 4}),
        }

class PostSearchForm(forms.Form):
    q = forms.CharField(label='Search', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import F
from django.shortcuts import redirect
from django.template.defaultfilters import title
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.text import slugify
from django.views.generic import ListView, DeleteView, DetailView, CreateView, UpdateView
from django.core.paginator import Paginator
from django.contrib import messages

from .forms import PostCreateForm, CommentCreateForm, PostSearchForm
from .models import *


# Create your views here.
class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        query_set = Post.objects.filter(is_published=True).select_related('author').order_by('-created_at')
        query = self.request.GET.get('q')
        if query:
            query_set = query_set.filter(title__icontains=query)
        return query_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = PostSearchForm(self.request.GET)
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments_list = Comment.objects.filter(post=self.object, approved=True).select_related('author')
        paginator = Paginator(comments_list, 5)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['comments'] = page_obj
        context['comment_form'] = CommentCreateForm()
        return context

    def get_object(self):
        post = Post.objects.prefetch_related('categories', 'tags').get(
            pk=self.kwargs['post_pk'],
            slug=self.kwargs['post_slug'],
        )
        Post.objects.filter(pk = post.pk).update(views=F('views') + 1)
        post.refresh_from_db()
        return post

    @method_decorator(login_required())
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentCreateForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = self.object
            new_comment.author = request.user
            new_comment.save()
            messages.success(request, 'Your comment has been successfully submitted and will be displayed after approval. ')
            return redirect(self.object.get_absolute_url())

        context = self.get_context_data()
        context['comment_form'] = form
        return self.render_to_response(context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'blog/post_create.html'
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.cleaned_data['title'])
        messages.success(self.request, 'Post successfully created.')
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.get_absolute_url()

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostCreateForm
    success_url = reverse_lazy('blog:post_list')
    template_name = 'blog/post_update.html'

    def form_valid(self, form):
        form.instance.slug = slugify(form.cleaned_data['title'])
        messages.success(self.request, 'Post successfully updated.')
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

    def get_success_url(self):
        return self.object.get_absolute_url()

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')
    template_name = 'blog/post_delete.html'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

    def get_success_url(self):
        return reverse_lazy('accounts:profile')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Post successfully deleted.')
        return super().delete(request, *args, **kwargs)

blog/templates/blog/post_create.html
{% extends 'base.html' %}

{% block title %}Create New Post{% endblock %}

{% block content %}
<h2>Create Post</h2>

<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="mb-3">
        {{ form.title.label_tag }}
        {{ form.title }}
        {{ form.title.errors }}
    </div>
    <div class="mb-3">
        {{ form.content.label_tag }}
        {{ form.content }}
        {{ form.content.errors }}
    </div>
    <div class="form-check mb-3">
        {{ form.is_published }}
        {{ form.is_published.label_tag }}
        {{ form.is_published.errors }}
    </div>
    <div class="mb-3">
        {{ form.categories.label_tag }}
        {{ form.categories }}
        {{ form.categories.errors }}
    </div>
    <div class="mb-3">
        {{ form.tags.label_tag }}
        {{ form.tags }}
        {{ form.tags.errors }}
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'base.html' %}

{% block title %} Delete Post {% endblock %}

{% block content %}
  <h1>Delete post {{ object.title }}"</h1>
  <p>Are you sure for deleting this post?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'blog:post_list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<article class="mb-5">
    <h1>{{ post.title }}</h1>
    <p class="text-muted">Author: {{ post.author.username }} | {{ post.created_at|date:"Y/m/d H:i" }}</p>
    <hr>
    <p>{{ post.content|linebreaks }}</p>
    <hr>
    <p class="text-muted">Views: {{ post.views }}</p>

    {% if user.is_authenticated and user == post.author %}
        <div class="mb-3">
            <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-sm btn-warning">Edit</a>
            <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-sm btn-danger">Delete</a>
        </div>
    {% endif %}

    <p>Categories:
        {% for category in post.categories.all %}
            <span class="badge bg-secondary">{{ category.name }}</span>
        {% endfor %}
    </p>
    <p>Tags:
        {% for tag in post.tags.all %}
            <span class="badge bg-info text-dark">{{ tag.name }}</span>
        {% endfor %}
    </p>
</article>

<section class="mt-5">
    <h4>Comments</h4>

    {% if comments %}
        {% for comment in comments %}
            <div class="border rounded p-3 mb-2">
                <strong>{{ comment.author.username }}</strong>
                <p>{{ comment.content }}</p>
                <small class="text-muted">{{ comment.created_at|date:"Y/m/d H:i" }}</small>
            </div>
        {% endfor %}

        <!-- Pagination for comments -->
        <nav aria-label="Comments pagination">
            <ul class="pagination justify-content-center">
                {% if comments.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ comments.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo; Previous</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&laquo; Previous</span>
                    </li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">Page {{ comments.number }} of {{ comments.paginator.num_pages }}</span>
                </li>

                {% if comments.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ comments.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">Next &raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Next &raquo;</span>
                    </li>
                {% endif %}
            </ul>
        </nav>

    {% else %}
        <p>No comments yet.</p>
    {% endif %}
</section>

{% if user.is_authenticated %}
    <section class="mt-5">
        <h5>Leave a Comment</h5>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="{{ comment_form.content.id_for_label }}" class="form-label">Comment</label>
                {{ comment_form.content }}
                {% if comment_form.content.errors %}
                    <div class="text-danger">
                        {{ comment_form.content.errors }}
                    </div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </section>
{% else %}
    <p class="mt-4">To leave a comment, please <a href="{% url 'accounts:login' %}">log in</a> first.</p>
{% endif %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block title %}Post List{% endblock %}

{% block content %}
    <h1 class="mb-4">Recently Posts</h1>
    {% for post in posts %}
        <div class="card mb-4">
            <div class="card-body">
                <h3>
                    <a href="{% url 'blog:post_detail' post.pk post.slug %}" class="text-decoration-none">
                        {{ post.title }}
                    </a>
                </h3>
                <p class="text-muted mb-1">
                    author: {{ post.author.username }} | {{ post.created_at|date:"Y/m/d H:i" }}
                </p>
                <p>{{ post.content|truncatewords:30 }}</p>

                <a href="{% url 'blog:post_detail' post.pk post.slug %}" class="btn btn-primary btn-sm">
                    Continue reading...
                </a>

            </div>
        </div>
    {% empty %}
        <p>No post has been published yet!</p>
    {% endfor %}
    <form method="get" class="mb-4">
        <div class="input-group">
            {{ search_form.q }}
            <button type="submit" class="btn btn-primary">search</button>
        </div>
    </form>

    <div class="pagination">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% endif %}
            </ul>
        {% endif %}
    </div>

{% endblock %}

blog/templates/blog/post_update.html
{% extends 'base.html' %}

{% block title %}Edit Post{% endblock %}

{% block content %}
  <h2>Edit Post</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Update</button>
  </form>
{% endblock %}